---
version: 2.1

commands:
  install_dependencies:
    steps:
      - run: gem install bundler -v '2.3.11'
      - restore_cache:
          keys: &gem_key etd-processor-cimg-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path ./vendor/bundle
      - save_cache:
          key: *gem_key
          paths:
            - ./vendor/bundle

jobs:
  build:
    working_directory: ~/etd-processor
    docker:
      - &ruby_docker
        image: cimg/ruby:3.1-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - install_dependencies
      - persist_to_workspace:
          root: &root '~/etd-processor'
          paths: '*'

  lint:
    working_directory: *root
    docker:
      - *ruby_docker
    steps:
      - attach_workspace:
          at: *root
      - run:
          name: Lint using RuboCop
          command: bundle exec rubocop

  test:
    working_directory: *root
    docker:
      - *ruby_docker
    steps:
      - attach_workspace:
          at: *root
      - run:
          name: Test using RSpec
          command: bundle exec rspec
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
